version: '3.8'

services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
    command: "redis-server --save 20 1 --loglevel warning --protected-mode no   --loadmodule /opt/redis-stack/lib/rejson.so"
    volumes:
      - 'redisdata:/data'
    
volumes:
  redisdata: