version: '3.8'

services:
  redis:
    image: 'redis/redis-stack:latest'
    container_name: redis-master
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'
    
volumes:
  redisdata: